### ISSUE TITLE
Add CCTK_HOST and CCTK_DEVICE for functions in Algo

### ISSUE THREAD

**Issue by lwJi** [eschnett/CarpetX#108]
Should we add CCTK_HOST and CCTK_DEVICE in front of those functions in Algo?
In AsterX/Con2PrimFactory, we called function `brent()` which requires us to add CCTK_HOST and CCTK_DEVICE to make it work with GPU.

**Comment by eschnett** [comment]
We can do that. Can you prepare a pull request, including test cases (see the function `Test_roots`) that run on the device?

**Comment by lwJi** [comment]
Will do

**Comment by lwJi** [comment]
CCTK_HOST and CCTK_DEVICE is still undefined in Algo, should I keep defining ALGO_HOST and ALGO_DEVICE myself and use them?
