### ISSUE TITLE
CarpetX/*Base and einsteinbase/*Base are mutually incompatible

### ISSUE THREAD

**Issue by SamuelCupp** [eschnett/CarpetX#130]
Currently, the various *Base thorns in CarpetX and *Base thorns in the toolkit are mutually incompatible. Since the standard is for all thorns to be able to compile at once and be switched at runtime, this should be resolved before including CarpetX in a release. A proposed solution is to change the new thorns by adding either an X or a 2 (i.e. ADMBase2 or ADMBaseX).

**Comment by eschnett** [comment]
The thorns were renamed.
