### ISSUE TITLE
Make ODESolvers aware of MultiPatch grids

### ISSUE THREAD

**Issue by lucass-carneiro** [eschnett/CarpetX#206]
Currently, `ODESolvers` fails to perform a time step with `MultiPatch` (see [MultiPatchWaveToy](https://github.com/lucass-carneiro/CapyrX/tree/main/MultiPatchWaveToy) and example parameter file therein to reproduce the issue) by failing the assertion.

```
last == var_groups.end()
```

in `ODESolvers/solve.cxx:690`. In this instance, `var_groups` is an array of 8 repeated elements, with each element being the number `6`.

**Comment by eschnett** [comment]
Closed via https://github.com/eschnett/CarpetX/pull/205.
