### ISSUE TITLE
TOV with AMR does not work after commit ee194cb

### ISSUE THREAD

**Issue by lwJi** [eschnett/CarpetX#73]
TOV with AMR used to work before commit `b673be9`. However, it generate the following error after commit `ee194cb`:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Assertion `nGrowVect().allGE(dnghost)' failed, file "/usr/local/include/AMReX_FabArrayCommI.H", line 332
```

This error would go away if we remove the last two arguments on line 202 in `CarpetX/src/fillpatch.cxx`:
```
mfab_crse_patch.ParallelCopy(cmfab, 0, 0, ncomps, IntVect{0}, nghosts,
```
->
```
mfab_crse_patch.ParallelCopy(cmfab, 0, 0, ncomps,
```

**Comment by eschnett** [comment]
Which parameter file is this?

**Comment by eschnett** [comment]
This has been corrected via https://github.com/eschnett/CarpetX/pull/85.
